---
abstract: 'Count the number of syllables in Norwegian words.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '7.24'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-NO-Syllable
requires:
  Exporter: '5.72'
  Unicode::Normalize: '1.25'
version: '0.06'
x_serialization_backend: 'YAML::Tiny version 1.69'
